server:
  port: 9901

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:9900/eureka/

spring:
  application:
    name: serverservice
  cloud:
    loadbalancer:
      retry:
        enabled: false
  datasource:
    url: jdbc:mysql://47.94.13.6:3306/demo?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: admin
    password: admin
mybatis:
  mapper-locations: classpath:mapper/**/*.xml