server:
  port: 9903

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:9900/eureka/

spring:
  application:
    name: zuulservice
  cloud:
    loadbalancer:
      retry:
        enabled: false

zuul:
  routes:
    server:
      path: /server/**
      serviceId: server-service
      sensitiveHeaders: "*"
    web:
      path: /web/**
      serviceId: web-service
      sensitiveHeaders: "*"